services:
  node-app:
    build: .
    #    image: ghcr.io/bumstaerk/docker-swarm-practice:latest
    container_name: node-appz
    environment:
      INSTANCE: "compose"
      PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"

